// Generated by CoffeeScript 1.6.3
(function() {
  var Calculator, root;

  Calculator = (function() {
    Calculator.METADATA_PER_DOCUMENT = 56;

    Calculator.OLD_METADATA_PER_DOCUMENT = 64;

    Calculator.SSD_STORAGE_TYPE = 'ssd';

    Calculator.SPINNING_STORAGE_TYPE = 'spinning';

    Calculator.DEFAULTS = {
      numOfDocuments: 1000000,
      idSize: 100,
      valueSize: 10000,
      numberOfReplicas: 1,
      workingSetPercentage: .2,
      metadataPerDocument: Calculator.METADATA_PER_DOCUMENT,
      storageType: Calculator.SSD_STORAGE_TYPE,
      highWaterMark: .7
    };

    function Calculator(options) {
      if (options == null) {
        options = {};
      }
      this.options = $.extend({}, this.constructor.DEFAULTS, options);
    }

    Calculator.prototype.numberOfCopies = function() {
      return 1 + this.options.numberOfReplicas;
    };

    Calculator.prototype.totalMetadata = function() {
      return this.options.numOfDocuments * (this.options.metadataPerDocument + this.options.idSize) * this.numberOfCopies();
    };

    Calculator.prototype.totalDataset = function() {
      return this.options.numOfDocuments * this.options.valueSize * this.numberOfCopies();
    };

    Calculator.prototype.workingSet = function() {
      return this.totalDataset() * this.options.workingSetPercentage;
    };

    Calculator.prototype.clusterRamQuotaRequired = function() {
      return Math.ceil(((this.totalMetadata() + this.workingSet()) * (1 + this._overheadPercentage()) / this.options.highWaterMark) / 1000000000);
    };

    Calculator.prototype._overheadPercentage = function() {
      if (this.options.storageType.toLowerCase() === Calculator.SPINNING_STORAGE_TYPE) {
        return .30;
      } else {
        return .25;
      }
    };

    Calculator.numberOfNodesNeeded = function(ramRequired, ramPerNode) {
      if (ramPerNode === 0) {
        return;
      }
      return Math.ceil(ramRequired / ramPerNode);
    };

    return Calculator;

  })();

  root = typeof exports !== "undefined" && exports !== null ? exports : window;

  root.Calculator = Calculator;

}).call(this);
